# Generated by Django 5.0.6 on 2024-06-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tode',
            new_name='Todo',
        ),
    ]
